### PR TITLE
Add GitHub Actions workflow for Kotlin code style checks

### LINKED ISSUE #3: [Cleanliness of the code] Add automated check, to ensure correct coding standards
## Description:
In pursuit of maintaining code quality and adherence to the Kotlin style guide, this issue aims to implement an automated check to ensure that all Kotlin code contributions meet the specified coding standards. This step will streamline the review process by automatically verifying code cleanliness before merging any changes.

## Objective:
The primary objective is to set up a mechanism that automatically checks Kotlin code against the Kotlin style guide using a linter or static analysis tool. This implementation aims to enforce consistent formatting, naming conventions, and best practices outlined in the Kotlin style guide.

## Additional Information:
The chosen tool, whether it's ktlint, Detekt, or any other preferred option, will need to be integrated into the GitHub workflow. Consider using GitHub Actions to execute these checks automatically whenever a pull request modifies Kotlin files in the repository.

### PR DESCRIPTION
**Pull request by PKrystian**
## Description: 
Added the workflow file '.github/workflows/code_style_check.yml'.  
Configured Detekt for code styling rules and ensured the setup for code style checks.  

## Notes:
 After merging the pr, I will check if the workflow works as intended.

### CODE REVIEW

**Comment by PKrystian** [comment]
## Update:
Fixing the workflow, for now please refrain from reviewing pr.

**Comment by PKrystian** [comment]
## Update:
Workflow fixed, now got 8 warnings/erros related to style check:
```kt
NewLineAtEndOfFile - [/home/runner/work/FiveNightsEscape/FiveNightsEscape/app/src/test/java/com/example/fivenightsescape/ExampleUnitTest.kt] at /home/runner/work/FiveNightsEscape/FiveNightsEscape/app/src/test/java/com/example/fivenightsescape/ExampleUnitTest.kt:1:1
NewLineAtEndOfFile - [/home/runner/work/FiveNightsEscape/FiveNightsEscape/app/src/androidTest/java/com/example/fivenightsescape/ExampleInstrumentedTest.kt] at /home/runner/work/FiveNightsEscape/FiveNightsEscape/app/src/androidTest/java/com/example/fivenightsescape/ExampleInstrumentedTest.kt:1:1
NewLineAtEndOfFile - [/home/runner/work/FiveNightsEscape/FiveNightsEscape/app/src/main/java/com/example/fivenightsescape/MainActivity.kt] at /home/runner/work/FiveNightsEscape/FiveNightsEscape/app/src/main/java/com/example/fivenightsescape/MainActivity.kt:1:1
NewLineAtEndOfFile - [/home/runner/work/FiveNightsEscape/FiveNightsEscape/app/build.gradle.kts] at /home/runner/work/FiveNightsEscape/FiveNightsEscape/app/build.gradle.kts:1:1
MagicNumber - [<anonymous>] at /home/runner/work/FiveNightsEscape/FiveNightsEscape/app/build.gradle.kts:8:18
MagicNumber - [<anonymous>] at /home/runner/work/FiveNightsEscape/FiveNightsEscape/app/build.gradle.kts:[12](https://github.com/PKrystian/FiveNightsEscape/actions/runs/7363956155/job/20043907880?pr=4#step:5:13):18
MagicNumber - [<anonymous>] at /home/runner/work/FiveNightsEscape/FiveNightsEscape/app/build.gradle.kts:[13](https://github.com/PKrystian/FiveNightsEscape/actions/runs/7363956155/job/20043907880?pr=4#step:5:14):21
NewLineAtEndOfFile - [/home/runner/work/FiveNightsEscape/FiveNightsEscape/build.gradle.kts] at /home/runner/work/FiveNightsEscape/FiveNightsEscape/build.gradle.kts:1:1	
```
Fxiging the styling issue now ( in this pr ).

**Comment by PKrystian** [comment]
## Update:
Workflow setup complete
Styling issues fixed

**Review by pmusielak — APPROVED** [review]
LGTM

**Pull request merged**
